### ISSUE TITLE
Set limitation to cache in `Player` for syncing

### ISSUE THREAD

**Issue by faiface** [hajimehoshi/oto#6]
As far as I can tell, currently it's possible to play audio, but there's no way to tell how much of it has already been processed, which makes it hard to time-synchronize audio playback.

I'm not sure about the concrete API, that needs to be figured out.

**Comment by hajimehoshi** [comment]
As for playing back, I've implemented that on `oto` (see the below link). I don't think `oto` should have such capability and I want to keep `oto` as simple as possible.

https://github.com/hajimehoshi/ebiten/blob/master/audio/audio.go

**Comment by hajimehoshi** [comment]
What the audio package does is, basically, write only a necessary bytes to oto for each frame e.g. 1/60 seconds.

**Comment by faiface** [comment]
I'm 100% for keeping simplicity, however I'm still not convinced that this is not a crucial feature.

Writing only the necessary data each frame will soon or later either become out-of-sync, or will cause occasional playback glitches, am I not right? The reasons are, that the framerate is not entirely stable and synchronizing playback just based on time is not 100% precise, so one side (sender / receiver) will soon or later get ahead of the other side.

**Comment by hajimehoshi** [comment]
> Writing only the necessary data each frame will soon or later either become out-of-sync, or will cause occasional playback glitches, am I not right?

Yes and no: Ebiten doesn't cause such glitches so far, but I admit this can happen technically.

> The reasons are, that the framerate is not entirely stable and synchronizing playback just based on time is not 100% precise, so one side (sender / receiver) will soon or later get ahead of the other side.

If you want to sync time and audio, you can use an independent go-routine for audio, can't you? Isn't the Go standard lib's timer precise enough?

**Comment by faiface** [comment]
Perhaps you're right. Just to be sure, I asked Pete Garcin on Gitter.

**Comment by hajimehoshi** [comment]
As we discussed on Pixel's gitter,

* `Write` never blocks.
* On OpenAL implementation, cache is limited and `Write` can refuse to write, but on other implementation, `Write` never refuses since a `Player` has an infinite cache.
* Synching with time is not reliable since playing audio might be delayed, so we want to know how many bytes are actually played. The problem is that there is no way to know such information in the current implementation.
* Actually, this is not only a concern but a real problem (hajimehoshi/ebiten#207). Writing bytes can be too fast and as a `Player` has infinite cache, audio would keep delayed for ever.
* The solution is to add limitation to cache of `Player` on all platforms.

**Comment by hajimehoshi** [comment]
As chatted with @faiface, we will add an argument to `NewPlayer` for a buffer size. We also need to write a doc about 'recommended' buffer size, which will be 1/10 [sec].

**Comment by hajimehoshi** [comment]
The new API depends on if we need to change the limitation dynamically.

**Comment by hajimehoshi** [comment]
Note that I didn't add an API to get default buffer size. I'm not sure this is really needed.
